### ISSUE TITLE
Manueller Checkin wird nicht als unterwegs angezeigt.

### ISSUE THREAD

**Issue by f2k1de** [derf/travelynx#101]
Nach dem Hinzufügen eines manuellen Checkins wird auf dem Profil "Aktuell nicht eingecheckt" angezeigt, auch wenn man von den Zeiten her gerade unterwegs ist.

**Comment by derf** [comment]
Ein nachvollziehbarer Wunsch; das ist allerdings by design.

travelynx unterstützt die Unterwegs-Ansicht aktuell nur für Fahrten zu denen es auch eine Datenquelle hat, manuelle Einträge sind damit außen vor. Für's erste wird das auch so bleiben.

**Comment by Ein-Tim** [comment]
Ich fänd das Feature auch cool, vielleicht können wir den Issue als Enhancement Request erneut öffnen? Oder wird das sicher nicht implementiert @derf?
