### ISSUE TITLE
Teilen eines manuellen Checkins nicht möglich.

### ISSUE THREAD

**Issue by f2k1de** [derf/travelynx#102]
Bei einem manuellen Checkin vermisse ich ein Buttonen um einen Link zu der Fahrt zu teilen und im Idealfall direkt in die Zwischenablage zu kopieren wie bei einem Checkin über das Depature Board "Ich bin gerade in … < link >"

**Comment by derf** [comment]
Wenn du die Fahrt in der History aufrust solltest du dort unten einen Teilen-Button finden.
