### ISSUE TITLE
Luftlinien Rückfalloption bei unbekannter Strecke wird nicht immer angezeigt

### ISSUE THREAD

**Issue by ColofoniusRegenschein** [derf/travelynx#103]
Leider scheint die Rückfalloption bei unbekanntem Streckenverlauf nicht immer dargestellt zu werden.

Hier ist als Beispiel eine Fahrt von Öhringen nach Karlsruhe mit der KVV S4:

![grafik](https://github.com/derf/travelynx/assets/29230963/4e945c3f-7157-4a29-a15e-51f7486fd218)

![grafik](https://github.com/derf/travelynx/assets/29230963/00f6e30b-bb48-414f-83ba-a1b376cddd4b)

Auch bei der Fahrt selbst wird nichts dargestellt:
https://travelynx.de/p/irgendEiner/j/525010?token=8004623-64-1700579220

**Comment by derf** [comment]
Should be fixed in f8542fffcd66ceba8ea0114181c942a45d3f8a0d

**Comment by ColofoniusRegenschein** [comment]
> Should be fixed in [f8542ff](https://github.com/derf/travelynx/commit/f8542fffcd66ceba8ea0114181c942a45d3f8a0d)

Yes, looks very good! Thanks for your work 👍
