### ISSUE TITLE
Reihungsdaten fehlen

### ISSUE THREAD

**Issue by jonaes** [derf/travelynx#109]
Hallo, 
aktuell fehlen die Reihungsdaten (werden nicht angezeigt und auch nicht gespeichert).
Konkretes Beispiel wäre der RE 16514 von heute (07.01.24). Der sollte eigentlich auf jedenfall welche haben > https://bahn.expert/details/16514/2024-01-07T10:14:00.000Z?administration=800456

**Comment by derf** [comment]
Manchmal kommen sie aus der API und manchmal gibt es Timeouts oder andere Fehler. Bitte Bescheid geben wenn der Fehler dauerhaft auftritt; an sich sollte es bis auf gelegentliche Ausnahmen funktionieren.
