### ISSUE TITLE
Travelynx vs. Träwelling

### ISSUE THREAD

**Issue by dereineLauch** [derf/travelynx#117]
Was soll ich nutzen, bzw. was ist besser?
Und warum wurde Travelynx entwickelt obwohl es schon Träwelling gab?

**Comment by derf** [comment]
Nutze was auch immer dir am besten gefällt.

Einerseits setzt travelynx andere Schwerpunkte als Träwelling.
Andererseits ist es ein Hobbyprojekt, somit "weil es geht".

**Comment by dereineLauch** [comment]
Vielen Dank für die schnelle Antwort.
Was sind denn die verschiedenen Schwerpunkte?
