### ISSUE TITLE
Web hooks for event

### ISSUE THREAD

**Issue by sirtux** [derf/travelynx#12]
Hi,

support for webhooks would be nice, 
which are triggered by events, eg:
- checkin
- train departure
- train arrival

I guess just POSTing to an URL with the content of https://travelynx.de/api/v1/status/ and having a bearer token for authentification would be sufficient.

**Comment by derf** [comment]
work-in-progress webhook support is available at https://travelynx.de/account/hooks, let me know if it works for you. departure/arrival events and a link from the account page will follow later.

**Comment by sirtux** [comment]
Works well - thank you very much.
A button for the ping would be great on the configuration page, or the save button doesn't change the page..
