### ISSUE TITLE
Kaputte Umbrüche an Köln Hbf

### ISSUE THREAD

**Issue by DasKadse** [derf/travelynx#121]
An den Gleisen 10 und 11 vom Kölner Hbf (S-Bahn) werden anstatt einer Wagenreihung teilweise angepasste Gleisnummern angegeben (siehe Bild). Das führt scheinbar bei den vorgeschlagenen Verbindungen, während man eingecheckt ist, zu komischen Umbrüchen bei den Linien. 

![umbruch_crop](https://github.com/derf/travelynx/assets/10179934/206d6e75-386a-4432-ab75-982a82840d0d)

**Comment by derf** [comment]
Fixed by d3f1d5a42abf24377a701aaf972e612e064dfc08
