### ISSUE TITLE
HTTP 500 beim Nahverkehr

### ISSUE THREAD

**Issue by Janfred** [derf/travelynx#126]
Beim Versuch in Syke den Nahverkehr anzuzeigen gibt es einen HTTP 500.

https://travelynx.de/s/8005809?hafas=1

```
Timestamp: 30/Mar/2024:09:35:42 +0100

Message: Invalid local time for date in time zone: Europe/Berlin 
```

**Comment by derf** [comment]
Sommerzeit lässt grüßen. WiP.

**Comment by Janfred** [comment]
Wieder mal ein perfektes Beispiel für den hier: https://xkcd.com/1883/

Danke für den schnellen Fix :heart:
