### ISSUE TITLE
HTTP 500 beim Aufruf der Seite

### ISSUE THREAD

**Issue by ham-jaky** [derf/travelynx#127]
> Timestamp: 31/Mar/2024:17:40:28 +0200
> 
> Message: Can't call method "clone" on an undefined value at lib/Travelynx/Helper/HAFAS.pm line 91.

Letzte Verbindung: SEV Bus
Keine Haltestelle ausgewählt (evtl. noch im SEV-Bus eingecheckt)

Ich hoffe, dass das alle relevanten Infos sind. :)

**Comment by ham-jaky** [comment]
Ok, gerade konnte ich eine Station auswählen, habe es gemacht und habe unter diesem Link: https://travelynx.de/s/8080750?hafas=0
Die gleiche Fehlermeldung bekommen.
`Timestamp: 31/Mar/2024:17:45:18 +0200`

**Comment by SpielenmitLili** [comment]
Dasselbe Problem bei mir mit Startseite

**Comment by lollar1337** [comment]
via API den Status mal abrufen?

**Comment by SpielenmitLili** [comment]
> via API den Status mal abrufen?

Da ist jetzt nichts ungewöhnliches zu sehen
![image](https://github.com/derf/travelynx/assets/74246564/69333eef-76c7-43fd-a2fd-158d464b2884)

**Comment by deingithub** [comment]
Observing this too, as soon as connections are shown, the page can't load anymore. Disabling connection suggestions in https://travelynx.de/account/insight seems to help.
I think this is the same issue as #128 and that this call in the connections is to blame:
https://github.com/derf/travelynx/blob/38e03bcc8815641eb57c9cd6137616938de43d5d/lib/Travelynx/Controller/Traveling.pm#L255-L259
The `get_departures_p` now assumes a `$opt{timestamp}` to be passed, this callsite doesn't.

**Comment by derf** [comment]
My bad. I deployed a new feature from EasterHegg 2024 and didn't test it thoroughly. Fixed by b978ba6bc0c1f429f02990c2439977b2bd4fbe42 and 6e42d1dc29ac3efbf06854c8fafd059bca5d99c4; deployed as of now. Thanks for the quick report.

**Comment by ham-jaky** [comment]
Thanks for the great Website and fast help!
