### ISSUE TITLE
Enhancement: Migrate to PWA

### ISSUE THREAD

**Issue by fabianhick** [derf/travelynx#13]
It would greatly improve mobile experience if travelynx would support some parts of a progressive web app.
E.g. travelynx could then be launched from the home screen of Android like a real app.

**Comment by derf** [comment]
Basic PWA support is available, please test :)

I won't add an offline mode though, so you'll have to live with the offline page when there's no reception.

**Comment by fabianhick** [comment]
Thanks! Seems fine to me :)

Only one button seems distorted, though it's like that in the web version as well.
![button](https://user-images.githubusercontent.com/16404121/57161148-1a730b00-6deb-11e9-9e33-2b43a45a3892.jpeg)

**Comment by derf** [comment]
Aye, fixed that too.
