### ISSUE TITLE
Bugrepor4

### ISSUE THREAD

**Issue by Feuergamer07** [derf/travelynx#131]
Guten tag. Die Haltestelle Meißen triebischtal karl-Niesner-Straße ist nicht verfürbar zum chechout  & checkin

**Comment by desvaters** [comment]
![image](https://github.com/derf/travelynx/assets/71886240/a6174a18-a335-4e85-a2ce-ccfcf529790b)
![image](https://github.com/derf/travelynx/assets/71886240/ac5f12fe-3209-48d2-8bcb-f79d048053c6)
Also bei mir existiert die Haltestelle, und ein- und auschecken konnte ich auch.

**Comment by derf** [comment]
Aktuell nicht reproduzierbar.
