### ISSUE TITLE
Straßenbahn Dresden 

### ISSUE THREAD

**Issue by Feuergamer07** [derf/travelynx#134]
Hallo
Die Dresdner strassenbahn linie stimmen viele Haltestellen nicht bzw sind seit einiger Zeit nicht  
 mehr als Checkin verfügbar .
Z.b. Linie 3 am wildermann Richtung coschütz.

**Comment by derf** [comment]
Tatsache. Das kommt so aus dem HAFAS-Backend, d.h. da kann ich leider auch nichts dran ändern.
