### ISSUE TITLE
Is showing the capacity icons twice intended?

### ISSUE THREAD

**Issue by Ein-Tim** [derf/travelynx#137]
I already noticed this last time, but today I noticed again and it seems odd, that the capacity indicators are shown twice. Here's a screenshot where you can see the "problem":

![image](https://github.com/derf/travelynx/assets/67682506/31afbf6c-46f9-4f6c-8e30-84eef2fa1844)

Is this intended?

**Comment by derf** [comment]
Hi!

That's indeed intended. The first icon from the left is for first class, the
second icon for second class.

**Comment by Ein-Tim** [comment]
@derf Ah, I understand! Thank you!
