### ISSUE TITLE
Enhancement: Add push messages for check-out

### ISSUE THREAD

**Issue by fabianhick** [derf/travelynx#14]
This could be a helpful reminder to prevent forgetting to check out.

**Comment by derf** [comment]
Is this still an issue? ffaa0c44a78bb4bab632fcb76b668215da4c0a82 introduced automatic check-out, so you can select the destination immediately after check-in and still get frequently updated real-time data during the journey and for check-out.

**Comment by fabianhick** [comment]
It isn't necessary but it could be a nice reminder, e.g. to check-in to the next train of the journey.

**Comment by derf** [comment]
Could be, yeah. But IMHO it's not worth the effort of implementing it -> wontfix for now
