### ISSUE TITLE
"Haltestellendaten" source links to 404 page

### ISSUE THREAD

**Issue by Ein-Tim** [derf/travelynx#143]
On this screen: 
![image](https://github.com/derf/travelynx/assets/67682506/07e4d28f-7938-4634-b025-7d8bcbc3a826)

The link to "Haltestellendaten" is http://data.deutschebahn.com/dataset/data-haltestellen. This is a 404 page.

**Comment by derf** [comment]
You can thank Deutsche Bahn for that. I'll check whether https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View&tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-haltestellendaten-xml&cHash=bce297de5c28920f8cf3df376f6f5cb5 is a suitable replacement at some point and remove the link if it is not.
