### ISSUE TITLE
Travelynx shows incorrect distance/speed 

### ISSUE THREAD

**Issue by amy1337** [derf/travelynx#145]
Hello,

I've noticed that sometimes the speed and distance for a train dispatch differs significantly from reality. In this example, travelynx shows a distance of 42km instead of 5.6km and an average speed of 358km/h instead of 48km/h (see screenshot). For the check-in I used the IRIS backend. 

Thanks for taking a look at it! :)

Link to the check-in: https://travelynx.de/p/amy/j/831127?token=8011113-226-1719081660.000000
![image](https://github.com/derf/travelynx/assets/94536378/cfe3e1f0-5dfc-4102-9b6b-ce8c7b0c37d1)

**Comment by derf** [comment]
Resolved in 9b7013907b8e7aeb9703c841c33ef337bdfbcece :)
