### ISSUE TITLE
Improvement proposal: Indication which DB backend is used

### ISSUE THREAD

**Issue by Ein-Tim** [derf/travelynx#148]
I really like that there are now multiple backends which I can choose from. However, I think it would be useful to have an indication on the home page to know wether I'm using DB IRIS or DB HAFAS.

So here, where it says "DB" I suggest adding "IRIS" or "HAFAS", depending on what the user has selected.

<img src="https://github.com/user-attachments/assets/42b27e0d-696c-40b8-9983-5dbcd84178b2" width="300">

If you don't think that's a good place to add that, maybe when having selected the station you could add that information in the top right corner, where currently it only says "DB"?

<img src="https://github.com/user-attachments/assets/3157be38-96fc-466b-a799-fd7332d77b31" width="300">

**Why do I want this?**

I think this is useful for users who plan on switching between HAFAS and IRIS often. I'm such a user, as I will record my trips with Bus, Tram & U-Bahn using HAFAS, but when I travel with the S-Bahn, I want the most detailed data so I have to use IRIS. Making it easier for the user to see which DB backend is currently selected would for sure safe me a lot of unnecessary tips because I wanted to change to IRIS while I already have IRIS selected.

**Comment by derf** [comment]
I had that; but it turned out that there wasn't enough horizontal space to write it out.

Right now the icon serves as indicator: IRIS has a train icon; HAFAS uses an arrow.

**Comment by Ein-Tim** [comment]
@derf Ahh, I see. That works out!
