### ISSUE TITLE
Wagenreihung

### ISSUE THREAD

**Issue by Feuergamer07** [derf/travelynx#149]
Seit einigen Tagen wir bei mir die wagenreihung der Züge (sbahn / re / Ic / ICE) nicht mehr erfasst. Dieses Problem ist schon einige tag.
Woran könnte es liegen?

**Comment by Ein-Tim** [comment]
Ist die Wagenreihung sowohl in HAFAS als auch in IRIS verfügbar oder nur in IRIS @derf? Falls nur IRIS das unterstützt, könnte ich mir vorstellen, dass @Feuergamer07 HAFAS nutzt (da das der Standard ist) & deswegen keine Wagenreihung mehr bekommt.

**Comment by Feuergamer07** [comment]
![Screenshot_20240730_214844_Chrome](https://github.com/user-attachments/assets/9fa72f2f-7e30-4915-8696-7eb863d03df6)
![Screenshot_20240730_214916_Chrome](https://github.com/user-attachments/assets/8f85ea63-8779-4943-ae3e-4625b43d40f4)




Hier z.b. nimmt es keine wagenreihung für den FV

**Comment by derf** [comment]
Die von travelynx genutzte Wagenreihungs-API ist tot. Ersatz folgt in ein bis zwei Wochen.

**Comment by Feuergamer07** [comment]
Wäre sehr nett wenn nicht lange dauert:)
