### ISSUE TITLE
Enhancement: Connect same stations with different names

### ISSUE THREAD

**Issue by fabianhick** [derf/travelynx#15]
Some train stations have different platform names. For example there is both `Stuttgart Hbf` and `Stuttgart Hbf (tief)`.

It would be useful to connect these in order to allow continuous tracking of the journey.

**Comment by derf** [comment]
For the record: Yup, that's an issue I intend to solve, I just didn't get around to it yet

**Comment by derf** [comment]
> It would be useful to connect these in order to allow continuous tracking of the journey.

By the way, what exactly do you mean by "connecting" them? travelynx is now able to show departures for Stuttgart Hbf when requesting Stuttgart Hbf (tief) and vice versa – is that the "connection" you were referring to?

**Comment by fabianhick** [comment]
Indeed, thank you!
