### ISSUE TITLE
Wagenreihung speichert nicht mehr im IRIS-TTS Backend

### ISSUE THREAD

**Issue by BundesbahnFan** [derf/travelynx#154]
Hi,
seit dem Backend-Update werden die Wagenreihungen beim Einchecken in eine Zugfahrt über DB IRIS leider nicht mehr gespeichert. 
Sie werden lediglich nach dem Einchecken vor der Abfahrt in Grau schematisch angezeigt, aber sind nach der Fahrt nicht in den Fahrtdetails sichtbar.
Beim DB HAFAS-Backend werden sie noch gespeichert. 
War das beim Update so beabsichtigt?

Vielen Dank im Voraus. 

Viele Grüße

**Comment by derf** [comment]
Ich habe in den letzten Tage nichts geändert. Die neue wagenreihungs-API ist allerdings ein bisschen flaky. Ggf. braucht es noch eine Anpassung, damit travelynx bei Fehlern mehrfach versucht, die Wagenreihung abzufragen.
