### ISSUE TITLE
Backends vereinfachen statt zu verkomplizieren

### ISSUE THREAD

**Issue by f2k1de** [derf/travelynx#156]
# Problem / Beobachtung
Ich habe die letzten Wochen über die Entwicklung gesehen, dass ein viel größerer Fokus als bisher auf die manuelle Backendwahl gelegt wird. 
Früher konnte man nur eher Nahverkehr (was aber auch FV Züge mit ein paar Abstrichen in den Daten konnte) und nur eher Fernverkehr (was keine Busse, U-Bahnen und Trams konnte) auswählen. 
Das hat für mich ganz gut funktioniert und bedürfte nur einer Umstellung wenn ich mal in einen Bus oder eine U-Bahn eingestiegen bin. 
Mittlerweile habe ich aber eine mehrere Bildschirmseiten lange Liste an möglichen Datenquellen - das überfordert mich einfach und erfordert dass ich dort auch vor jedem Checkin mir Gedanken zu machen muss und bewusst einen auswählen muss (und dazu auch erstmal das Wissen haben muss, in welcher Datenquelle ich jetzt was genau bekomme und was nicht). Das macht nicht nur den Checkin in einem crowded Verkehrsmittel schnell überfordernd, sondern macht das ganze auch nicht mehr so simpel wie bisher und eben auch nicht mehr für den wenig wissenden Endanwender einfach zu benutzen. 
Mittlerweile finde ich in manchen Backends auch gar nicht mehr meinen U-Bahnhof oder bekomme dort komische Daten raus - das ist eine Verschlechterung zu vorher für mich.

# Mögliche Lösung
Ich würde mir wünschen, dass in der Software versucht wird die Backends miteinander zu verbinden, sodass ich einfach in eine Haltestelle einchecken kann und dann dort die Daten aggregiert werden bzw. automatisch das passendste Backend für mein Verkehrsmittel was ich nehmen will rausgesucht wird. 
Somit muss ich mir dann nicht vor jedem Checkin viele Gedanken dazu machen, sondern kann einfach simpel einchecken. Die Daten scheint es ja zu geben, sie müssen halt nur in ein einheitliches Format gebracht werden - und es verhindert dass ich dann ausversehen ein falsches, für mich unvorteilhaftes Backend auswähle. 
Das würde den Check-in Prozess wieder sehr vereinfachen und auch der Datenqualität zuträglich sein.

**Comment by derf** [comment]
Eine Verknüpfung von Backends wird es vorerst nicht geben.

Demnächst wird travelynx allerdings anhand der eigenen Koordinaten und der Abdeckungskarten geeignete Backends voschlagen. Die Auswahl bleibt manuell – es gibt zu viele Feinheiten, als dass diese sich mit vertretbarem Aufwand automatisieren ließe.

**Comment by Ein-Tim** [comment]
@derf FYI: Da ist ein Typo in deinem letzten Commit, "lieern" statt "liefern".
