### ISSUE TITLE
Bug? Ganz abweichender Endhalt beim SEV Bus

### ISSUE THREAD

**Issue by SpielenmitLili** [derf/travelynx#159]
Hier eine Fahrt mit einem SEV Bus von der HLB

Die Fahrt ging eigentlich wie man in der Route sieht von Wetzlar nach Limburg. Im bahn.expert kann die Fahrt auch mit den Halten ganz normal nachgesehen werden.

Hier einmal wie es bei mir in Travelynx aussieht: 
![image](https://github.com/user-attachments/assets/0ef292cd-77dc-4063-b3af-772423997e5f)

Jedoch hat sich der Endbahnhof in Travelynx irgendwie in "Hamburg Wandsbeker Chaussee" geändert? Ist oben unter "Fahrt von x nach y am Datum" zu sehen. Dementsprechend ist die berechnete Geschwindigkeit vollkommen falsch und auch die Strecke. Und naja auf der Karte wie man sich sicher denken kann. 

Hatte das schon jemand, weiß man wie es dazu kommt und woran das liegt?

**Comment by derf** [comment]
Das sollte nicht sein™

Darf ich mir den zugehörigen Datenbank-Eintrag anschauen? Falls ja bräuchte ich dazu einmal die Journey-ID – das ist die Zeile oberhalb vom "Teilen"-Knopf.

**Comment by SpielenmitLili** [comment]
Sure darfst du. 
Das würde einmal die: 936016

**Comment by derf** [comment]
Es ist eine Regression in 47f76da4f8cc31146d2834dfdf9731d330288c9d – Bei IRIS-Checkins mit Stationen die travelynx nicht kennt werden seitdem fehlerhafte Stationen für den Checkin gespeichert, nämlich immer die am ähnlichsten heißt.

Wird bei Zeiten behoben und die betroffenen Reisen in der Datenbank gefixt. Bis dahin für SEV und Fahrten im Ausland bitte DB (HAFAS) ode ÖBB (HAFAS) nutzen.

**Comment by SpielenmitLili** [comment]
Achso, alles klar. 
Vielen Dank für die Rückmeldung ^^

**Comment by Ein-Tim** [comment]
@derf Ich vermute diese Regression führt auch zu dem Problem das auf meiner History einige Fahrten, die dort bereits schonmal eingezeichnet waren, nun nicht mehr eingezeichnet sind? 

Das ist die Meldung, die ich erhalte:
![image](https://github.com/user-attachments/assets/774b5ee5-be22-40fc-a4a7-61443554f769)

Wenn ich auf die einzelnen Fahrten komme sind die Details dort zwar richtig & die Karte zeigt auch korrekt per rotem Kreis Ein- und Aussteigsstation an, die Verbindungslinie der Punkte fehlt aber.

Wenn du denkst, dass das ein komplett anderer Issue ist öffne ich auch gerne einen neuen.
