### ISSUE TITLE
'error': 'add_journey failed in api/v1/import

### ISSUE THREAD

**Issue by fhennies** [derf/travelynx#162]
I am using a script to import connections manually and this (after not having been used for a time) today produced an error: 

`{'deprecated': False, 'error': 'add_journey failed: DBD::Pg::st execute failed: ERROR:  null value in column "backend_id" of relation "journeys" violates not-null constraint\nDETAIL:  Failing row contains (959565, 5119, R, , 1331, manual, 7400115, 2024-09-05 18:55:22+02, 2024-09-04 13:38:00+02, 2024-09-04 13:38:00+02, 8601309, 2024-09-05 18:55:22+02, 2024-09-04 14:29:00+02, 2024-09-04 14:29:00+02, f, 16383, null, null, [["Lund Central", 7400115, {"lat": 55.70661, "lon": 13.18639}], ..., null, {"comment": "Beliebiger Text"}, null, null, null). at lib/Travelynx/Model/Journeys.pm line 265.\n', 'success': False}`

However, according to the documentation no backend info should be needed and adding the backend section doesnt help either

**Comment by homologic** [comment]
I can confirm this issue. It also occurs when fed with json exported from export.json, then it returns `{"deprecated":false,"error":"missing fromStation or toStation","success":false}`. Has the API changed?
