### ISSUE TITLE
Fahrgastrechteauskunft bei Verspätung von 20-59 Minuten

### ISSUE THREAD

**Issue by LilaHexe0** [derf/travelynx#163]
Ich habe ein Deutschlandticket, und bin relativ oft im Nahverkehr unterwegs. Wenn ein Zug >= 20 Minuten, aber <60 Minuten verspätet ist, kann ich die Verspätungszeit trotzdem anteilig "ansammeln", und zusammen mit anderen Verspätungen dann die 1,50EUR pro 60 Minuten Entschädigung beantragen.

(Mehr Infos dazu unter [Ich habe ein Monatsticket. Kann ich für eine Verspätung trotzdem Geld verlangen?](https://www.verbraucherzentrale.de/wissen/reise-mobilitaet/unterwegs-sein/erstattung-bei-zugverspaetung-so-gibts-geld-zurueck-12080))

Aktuell werden bei der Fahrgastrechtenansicht nur Verspätungen von >=60 Minuten angezeigt, und daher muss ich das (vermutlich) manuell per CSV machen. Könnte man vielleicht ein Schalter irgendwo einbauen, dass man die Verspätungen ab 20 Minuten anzeigt?

**Comment by Ein-Tim** [comment]
- Ist das ein Duplikat von https://github.com/derf/travelynx/issues/73?

**Comment by LilaHexe0** [comment]
Yeeeep, ist es. Habe anscheinend genau die falschen Keywords benutzt bei der Suche, danke!

**Comment by Ein-Tim** [comment]
@LilaHexe0 Kein Ding, es gibt auch bereits eine PR zu dem Thema, hier steht aber noch ein Review aus. - https://github.com/derf/travelynx/pull/116
