### ISSUE TITLE
Email confirmation Mail not sent

### ISSUE THREAD

**Issue by coolultra1** [derf/travelynx#166]
It seems the email containing the URL to complete isn't sent out currently and hasn't been for some weeks.

**Comment by derf** [comment]
travelynx sends Mail from a generic cloud host IP range; some providers do not like that unfortunately. Mails are being sent out and signups are working.

I can only suggest checking your spam folder or trying with a different mail provider (and, specifically, not using anything hosted at Microsoft, e.g. hotmail, live, outlook and similar domains). Sorry about that.
