### ISSUE TITLE
Add Mobiliteit.lu backend

### ISSUE THREAD

**Issue by SpielenmitLili** [derf/travelynx#167]
Wäre es möglich mobiliteit.lu als Backend hinzuzufügen?

Sie scheinen auch HAFAS zu verwenden: https://github.com/Felix3qH4/Mobiliteit.lu-API-documentation

Würde alle Züge in Luxemburg mit Livedaten versorgen sowie die RGTR Busse, die von anderen Providern nicht angezeigt werden darstellen.

**Comment by derf** [comment]
Sieht gut aus. Support für mobiliteit.lu ist im Hintergrund nun mit https://github.com/derf/Travel-Status-DE-DeutscheBahn/commit/d434735124d0ba86e6484da8adc4accb2430c3d0 möglich; travelynx wird das Backend im nächsten Release voraussichtlich ebenfalls unterstützen.

**Comment by SpielenmitLili** [comment]
Das klingt doch super. Ich freue mich drauf :3
