### ISSUE TITLE
Feature wish: Manually add journeys/trains (which are not in any information system)

### ISSUE THREAD

**Issue by dreirund** [derf/travelynx#175]
I have the feature wish to be able to completely manually add journeys (manually add trains, departure, end, intermediates ...).

For cases where the journey is not in any information system. Like some "Sonderfahrt", or some local train outside Germany (the InterRail app (which I do not use) has for such situations a similar functionality), or if one wants to record a day of travel in complete and so wants to include a footway.

Regards!

**Comment by derf** [comment]
Hi!

You can already do so: head to history and then use the Rohdaten → Neue Fahrt.

**Comment by dreirund** [comment]
> You can already do so: head to history and then use the Rohdaten →
> Neue Fahrt.

Thanks!

Sorry that I did not find it -- I did not expect "history" to be the
place to actually put something in.

Regards!
