### ISSUE TITLE
Feature-wish: Be able to (pre-)record multiple trips in the future.

### ISSUE THREAD

**Issue by dreirund** [derf/travelynx#178]
I hereby feature-wish that not only one check-in can be made at a time, but that also travel legs in the future can be pre-selected.

Use case: If a travel with several legs is planned, put in all at once at the beginning, and no need to get on the laptop later on.

If connections did break, there is still the possibility to edit after the fact, as it is already now.

*(This actually is the one feature which that I really praise in Träwelling, making life much easier there with regard to record non-past data.)*

Regards!

**Comment by derf** [comment]
That's an idea for the very long run, but may or may not happen in the next few years. I have way less time than I'd like to have.

I'll close this as not planned for now.
