### ISSUE TITLE
500 nach Auswahl des Bahnhofs

### ISSUE THREAD

**Issue by ham-jaky** [derf/travelynx#179]
Was habe ich gemacht:

1. Aus vorheriger fahrt ausgescheckt
2. Auf die Auswahl-Seite der Bahnhöfe in der Nähe weitergeleitet worden.
3. Über die Auswahl Berlin Ostbahnhof ausgewählt: `https://travelynx.de/s/8010255?hafas=DB`

Dabei ist folgender Fehler gekommen:
```
500 Internal Server Error
Das hätte nicht passieren sollen.


Angaben für einen Bug-Report:

Timestamp: 26/Oct/2024:17:14:08 +0200

Message: svcResL[0].err is CGI_READ_FAILED
```

Gestern bei diesem Timestamp `Timestamp: 25/Oct/2024:17:44:47 +0200` den gleichen Fehler bekommen. (`travelynx.de/s/8000152?hafas=DB`)

In beiden Fällen ist der Fehler auch nach refresh aufgetreten und war nach kurzer Zeit weg.

**Comment by Thunkkk** [comment]
Same here.
Website geöffnet, über Bahnhöfe in der Nähe "Itzehoe" ausgewählt.

Nach zwei Mal neu laden der Seite funktioniert es wieder.

Angaben für einen Bug-Report:

Timestamp: 03/Nov/2024:10:45:31 +0100

Message: svcResL[0].err is CGI_READ_FAILED

**Comment by kleinesfilmroellchen** [comment]
Selber Fehler:

Timestamp: 11/Nov/2024:16:29:13 +0100

Message: svcResL[0].err is CGI_READ_FAILED

**Comment by derf** [comment]
Das ist ein HAFAS-Fehler; travelynx kann hier nichts tun. Meist reicht es, die Anfrage nach einigen Sekunden bis Minuten nochmal zu stellen.

Ich passe mal die Fehlermeldung an, damit das klarer wird.
