### ISSUE TITLE
falsche Bahnhofsanzeigen

### ISSUE THREAD

**Issue by tciberlin** [derf/travelynx#180]
Hi,

mir ist gerade ein Fehler aufgefallen, wo ich nicht ganz nachvollziehen kann, einer herkommt. In der Titelleiste bei der Fahrtauswahl steht, dass ich auf der Seite von Jüterborg sein soll, bin aber tatsächlich in Berlin Hbf. Es werden auch die Abfahrten von Berlin Hbf angezeigt. Als Backend habe ich HAFAS der BVG genommen.

 ![image](https://github.com/user-attachments/assets/bde12c0c-f6e7-4a72-9e52-8c773e347665)

Vielleicht kannst Du damit ja was anfangen bzw. reproduzieren.

**Comment by derf** [comment]
Der Bugfix wird im Laufe der nächsten Wochen auf travelynx.de auftauchen.

**Comment by tciberlin** [comment]
Ich danke Dir 😄
