### ISSUE TITLE
No live updates of data in some edge cases

### ISSUE THREAD

**Issue by Ein-Tim** [derf/travelynx#183]
It seems like there is some weird edge case which causes travelynx to not pull live updates for some stations from IRIS. I have experienced this once or twice in the past and now again.
To make it more understandable what the problem is, here is what I experienced today:
I checked into the **ICE 725** to München Hbf. I checked in at "Frankfurt (Main) Hbf". I checked in as early as possible, as the train was delayed, this was ca. 65 minutes before departure.
Now travelynx shows that the ICE has left Frankfurt at 18:49, while actually we have left Frankfurt at 18:54. This can also be confirmed by taking a look at bahn.expert ([link to the journey](https://bahn.expert/details/ICE%20725/?journeyId=20241118-d65e82b8-65d1-3924-adf9-b4ebee367916)). 
I confirmed that I checked into the ICE using IRIS.

Here's a screenshot of the problem. Take a look and compare the times of departure which are shown on bahn.expert and on travelynx.
<img width="1440" alt="Bildschirmfoto 2024-11-18 um 19 38 54" src="https://github.com/user-attachments/assets/57f611ba-649a-480a-8575-f8534c8c396e">

**Comment by Ein-Tim** [comment]
Today again:

<img src="https://github.com/user-attachments/assets/9374d098-70ac-46c1-9d6c-31f3345f7101" width="300">

<img src="https://github.com/user-attachments/assets/5fd752eb-9c8f-4ef6-ac35-c7a9bd1f1735" width="300">

This time, I checked in ca. 2 minutes before the scheduled departure.

**Comment by Ein-Tim** [comment]
Tried whether checking out and back in to the trip or via bahn.expert solves this, it does not.

**Comment by derf** [comment]
According to IRIS data, EC 110 / RJ 110 departed Salzburg Hbf on time at 20:00.

So it looks like the backend used by bahn.expert is slightly more accurate than IRIS data in some cases, or IRIS data quality has degraded – the backend is so deprecated that it looks like Deutsche Bahn is actually considering to determine a date at which they will put it out of service.

You can try whether switching to HAFAS gives you higher data fidelity. If that does not help either, there's nothing I can do with the APIs I currently have at my disposal.

**Comment by Ein-Tim** [comment]
@derf

> So it looks like the backend used by bahn.expert is slightly more accurate than IRIS

Oh, that's new to me! I always thought that bahn.expert uses IRIS too. Now I also understand the README of https://github.com/marudor/bahn.expert better.

It's also very interesting that DB is considering shutting down IRIS, thanks for letting me know! 
May I ask whether you know if they plan to replace it with HAFAS or some completely new API?

> You can try whether switching to HAFAS gives you higher data fidelity.

Sounds good, I will try that. 

> If that does not help either, there's nothing I can do with the APIs I currently have at my disposal.

Absolutely understandable, thank you so much for your response.

Have a nice evening!

**Comment by derf** [comment]
Unfortunately, DB HAFAS is also deprecated, at least as far as I am aware.

bahn.de, DB Navigator and related services have switched to a custom family of APIs called RIS::Boards, RIS::Journeys, etc. – see https://developers.deutschebahn.com/db-api-marketplace/apis/product → "RIS-API". I know how to get started with them, but doubt that I'll get around to that within the next months. Unlike HAFAS and EFA, the RIS family of APIs is DB-specific, so implementing them is relatively thankless work that I'll likely postpone until both HAFAS and IRIS are offline or very close to being offline.

Have a nice evening as well, I hope my first reply didn't come off as overly harsh :)

**Comment by Ein-Tim** [comment]
> Unlike HAFAS and EFA, the RIS family of APIs is DB-specific, so implementing them is relatively thankless work that I'll likely postpone until both HAFAS and IRIS are offline or very close to being offline.

Very understandable and very unfortunate of Deutsche Bahn that they are going some special way here...

Don't worry about your first reply, it wasn't harsh at all!
