### ISSUE TITLE
Extremely flaky experience when checking in

### ISSUE THREAD

**Issue by Ein-Tim** [derf/travelynx#184]
Yesterday and today I almost always get the 502 error when trying to check in using DB HAFAS.
I just retry multiple times and after 10-20 attempts it normally works. 

Are you aware of any changes of DB HAFAS which would cause this issue or some planned downtime/maintenance with their backend?

Error details always are: 
```
Details:

svcResL[0].err is CGI_READ_FAILED
```

**Comment by derf** [comment]
I'm aware of the flakiness, but not of any more than that. It may or may not be related to the fact that DB HAFAS is kinda deprecated.

For now, you can check in via IRIS or a local (non-DB) HAFAS as a workaround. ÖBB HAFAS also tends to be a relatively good replacement. I'll roll out adjustments to hopefully increase the rate of successful HAFAS requests tomorrow.
