### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by mettaphysicist** [derf/travelynx#185]
Trying to find departing trains and check in, I get errors 502 or this time

500 Internal Server Error
Das hätte nicht passieren sollen.
[bug_reportBUG MELDEN](https://github.com/derf/travelynx/issues)
Angaben für einen Bug-Report:

Timestamp: 04/Dec/2024:17:31:41 +0100

Message: Request timeout

**Comment by derf** [comment]
That's a problem with DB HAFAS which has been going on for a few days already. Unfortunately, there's nothing I can do about it. You can re-try or use a different backend such as IRIS, ÖBB HAFAS, or a local HAFAS instance.

**Comment by mettaphysicist** [comment]
Thank you! Just stumbled across the different backends myself, indeed works like a charm again with a different one.Am 04.12.2024 um 17:54 schrieb Birte Friesel ***@***.***>:﻿
That's a problem with DB HAFAS which has been going on for a few days already. Unfortunately, there's nothing I can do about it. You can re-try or use a different backend such as IRIS, ÖBB HAFAS, or a local HAFAS instance.
