### ISSUE TITLE
Unable to use GPS Nearby stations due to internal error

### ISSUE THREAD

**Issue by Der-Flip** [derf/travelynx#186]
This is happening for a couple of months now.

I have travelynx installed to homescreen via Firefox. Every time I use the stations near me button, and selecting one of the offered options it throws this error

`svcResL[0].err is CGI_READ_FAILED`

When I use the manual search everything works as expected.

**Comment by Ein-Tim** [comment]
Just FYI: This is nothing specific to using the location based search feature, this also happens to me when searching manually:
https://github.com/user-attachments/assets/7124943e-b548-4e54-8cb0-0eb3db290654

See also:
- #185
- #184

**Comment by Der-Flip** [comment]
Oh, hadn't encountered those for now.
I looked for issues but didn't check the closed ones; my bad.

I guess changing to IRIS then?... I only logged train rides in travelynx anyways.

**Comment by Ein-Tim** [comment]
Yes, I'd suggest using IRIS in this case

**Comment by derf** [comment]
Like @Ein-Tim said: that's a backend issue; there's nothing I can do about it unfortunately. Switching to IRIS is the best option in your case.
