### ISSUE TITLE
Enhancement: Add ticket check statistic

### ISSUE THREAD

**Issue by fabianhick** [derf/travelynx#19]
Travelling on a time ticket it would be interesting to see how often your ticket has been checked while riding trains.

**Comment by derf** [comment]
There's lots of interesting statistics one could collect, so I'd rather not have a specific feature just for this.

I'll add a comment field which can be filled in after (and perhaps already during) a journey. This way, you can devise a format for ticket checks and anything else you'd like to note down, export the journeys in JSON or CSV format and do your own parsing to gather whatever statistics you like.

Of course, that's more tedious than built-in support, but I think it'll help keep the travelynx codebase itself clean and maintainable.

**Comment by TechMoritz** [comment]
> I'll add a comment field which can be filled in after (and perhaps already during) a journey. 
It would be very nice to add comments during the trip. Is there an update on the current status?

**Comment by derf** [comment]
Implemented and deployed :)
