### ISSUE TITLE
Enhancement: Use Travelynx abroad

### ISSUE THREAD

**Issue by TechMoritz** [derf/travelynx#20]
It would be great if you could define your own stations when adding journeys manually.

**Comment by TechMoritz** [comment]
I also noticed that GPS data is often missing abroad. Is there a solution for that?

**Comment by derf** [comment]
> It would be great if you could define your own stations when adding journeys manually.

That's a wontfix, sorry. travelynx uses a station database shared with other projects and I intend to keep it that way.

> I also noticed that GPS data is often missing abroad. Is there a solution for that?

It's being worked on. If you want to help (or add more stations), please open a pull request on https://github.com/derf/Travel-Status-DE-IRIS/blob/master/share/stations.json
