### ISSUE TITLE
Bug: Validation failed for type named Num declared in package Specio::Library::Builtins 

### ISSUE THREAD

**Issue by twiddau** [derf/travelynx#21]
Timestamp: 06/Oct/2019:00:36:48 +0200

Message: Validation failed for type named Num declared in package Specio::Library::Builtins (/srv/www/travelynx/local/lib/perl5/Specio/Library/Builtins.pm) at line 139 in sub named (eval) with value DateTime={ formatter: undef, local_c: { day: 6, day_of_quarter: 6, day_of_week: 7, day_of_year: 2...

---
User: Twi

The error message occurs as soon as I try to open Travelynx via https://travelynx.de/. So Travelynx is currently unusable for me.

Before the error occured, I tried to re-check in into ICE 619 (Frankfurt Flughafen Fernbf to Karlsruhe), after I already checked in and checked out of the train approx 0:45h before (Montabaur to Frankfurt Flughafen Fernbf).  

This train has two stops at the same station at two different times and the first stop doesn't have a departure time in RIS:
![image](https://user-images.githubusercontent.com/1540249/66261740-236d6b80-e7d3-11e9-9031-7f772fc12778.png)

Maybe it is related to this special use case.

I already tried to delete the first check-in, but this didn't resolve the problem.

**Comment by derf** [comment]
Should be fixed in e97c943154c2f025b85f3cde417ccb8d412df3e1, which has just been deployed on travelynx.de. The bug applied to all trains which have a stop more than once.

Thanks for reporting!
