### ISSUE TITLE
"eingechecked" Seite Design

### ISSUE THREAD

**Issue by marudor** [derf/travelynx#22]
![Screenshot_20191011-102322](https://user-images.githubusercontent.com/1881725/66637910-4bfec680-ec14-11e9-9071-bc04a17178e9.png)

As you can see design on small devices is a bit broken
(Huawei Honor 5 in this case)

**Comment by derf** [comment]
Should be fixed now (at least according to Chrome's device toolbar for a Galaxy S5), can you confirm that?

**Comment by marudor** [comment]
It's fixed.
