### ISSUE TITLE
Enhancement: Karte der History

### ISSUE THREAD

**Issue by Knuspel** [derf/travelynx#23]
Ich fände ein Feature cool worin die History auch auf einer Karte abgebildet wird.
Die Daten hierfür gibt es bei OSM.
Ein solches Tool konnte ich bisher nicht finden und würde die hier gesammelten Daten gut ergänzen.

**Comment by derf** [comment]
Ack. Wenn ich mal Lust habe, mich mit der Kombination aus OSM und Javascript auseinanderzusetzen, könnte das durchaus passieren.

**Comment by derf** [comment]
:heavy_check_mark: Siehe <https://travelynx.de/history/map>. Filtermöglichkeiten nach Zeitraum und Links auf den Monats- und Jahresseiten folgen demnächst.
