### ISSUE TITLE
When manually entering a journey that was cancelled, an actual departure and arrival time is required, although that doesn't necessarily make sense

### ISSUE THREAD

**Issue by moschlar** [derf/travelynx#25]
When manually entering a journey that was cancelled, an actual departure and arrival time is required, although that doesn't necessarily make sense

**Comment by moschlar** [comment]
Actually, it would be nicest if the actual dep/arr fields weren't required at all - if they are left empty, it could just be assumed that the train was on time (or that data is simply not available anymore).

**Comment by derf** [comment]
I'll implement the former variant – travelynx assumes that schedule and realtime data are always available (unless the train was cancelled, of course); changing that would require lots of special cases which are IMHO not worth the effort.

**Comment by moschlar** [comment]
Thanks!
