### ISSUE TITLE
Map doesnt't draw lines reliably

### ISSUE THREAD

**Issue by Knuspel** [derf/travelynx#26]
* The new map feature seems to not reliably draw the lines between stations yet.
![grafik](https://user-images.githubusercontent.com/57443990/69038948-3dfa4d80-09eb-11ea-99c6-46bc2a13921e.png)
* Additionally I'm curious if one could add the route of a train when manually adding a journey. That would make the map prettier but also provide more info about where one went.

**Comment by derf** [comment]
At the moment, lines between manually entered stations (or stations with bogus data) are deliberately left out. This is not final.

Providing the route when manually adding (or editing) a trip is on the todo list, but might take a while (it's a pretty boring chore)

**Comment by derf** [comment]
Both lines for incomplete routes (using a toggle on the map screen, disabled by default) and manual route entry are supported now
