### ISSUE TITLE
Enhancement: Mark a journey/train as cancelled

### ISSUE THREAD

**Issue by biolauri** [derf/travelynx#27]
I checked into a train from _Frankfurt (Main) Hbf_ to _Nürnberg Hbf_ and after checking in, the train got redirected to _Frankfurt (Main) Südbahnhof_, so for me, the whole train got cancelled (as I couldn't make it in time to _Südbahnhof_.

Unfortunately, Travelynx didn't handle this, keeping me checked in (with no real time data at _Frankfurt (Main) Hbf_, but with real time data from _Nürnberg Hbf_). So since I checked in to the next train, I get a warning in the statistics that my data are inconsistent as I've been checked into two trains at the same time.

I want to keep the entry to track its cancelled state, so I want to ask if it's possible to get the checkbox for a cancelled train also on checked-in trains (as it's currently only available for manual entries).  
Or is it some other bug I ran into?

**Comment by derf** [comment]
Hi!

You didn't run into a bug per se; support for the different kinds (and meanings) of train cancellations and route changes is lacking. I intend to devise a (hopefully sensible) way to deal with them and cases such as yours soon-ish. Until then, adding the checkbox to the journey editor is a good idea.

**Comment by biolauri** [comment]
Wow, that was quick! Thank you very much! Works like a charm. 🙂
