### ISSUE TITLE
Checkout when you change trains buggy

### ISSUE THREAD

**Issue by marudor** [derf/travelynx#29]
Stations that have multiple areas (for instance Frankfurt Hbf and Frankfurt Hbf (Tief) or Berlin Hbf (Tief), Berlin Hbf and Berlin Hbf (S-Bahn)) are a problem for the checkout when you change trains.

As you only do the auto checkout 10 minutes after arrival I'm often still checked in when I check into the new train. Doing that will check me out at the new Station, not at the arrived station.
This will result in logs that tell me I travelled from Karlsruhe Hbf to Frankfurt Hbf (Tief) (not possible)

<img width="1031" alt="Screenshot 2019-12-23 at 10 05 48" src="https://user-images.githubusercontent.com/1881725/71347968-cf6d5a00-256b-11ea-9fbc-37ab701260dc.png">
<img width="972" alt="Screenshot 2019-12-23 at 10 06 07" src="https://user-images.githubusercontent.com/1881725/71348001-dc8a4900-256b-11ea-8272-5db572702b78.png">

This most likely results in broken statistics & broken data for the map? (The connection Frankfurt Hbf -> Berlin Hbf is missing on the map)
It will also result in broken details for this connection. It can not correctly map where I left.
<img width="567" alt="Screenshot 2019-12-23 at 10 07 07" src="https://user-images.githubusercontent.com/1881725/71348092-0f344180-256c-11ea-9160-84c2b1846207.png">

Suggestion:
Use the meta station data to map the data. And use a station that is on the via of a train for the checkout.

**Comment by derf** [comment]
Fixed in v1.12.0
