### ISSUE TITLE
Enhancement: Adding and deleting trips manually

### ISSUE THREAD

**Issue by TechMoritz** [derf/travelynx#3]
It would be nice if you could add and delete train trips afterwards.

**Comment by derf** [comment]
I'll add support for trip deletion (and perhaps editing of arrival/departure time in case of backend issues) eventually.

What do you need manual trip entry for, though? IMHO, the whole purpose of travelynx is not having to do that manually.

**Comment by TechMoritz** [comment]
I would like to use travelynx for an overview of all train trips (possibly also with statistics). Sometimes I forget to check in. I would also like to add old trips so that it is complete :)

**Comment by fabianhick** [comment]
I personally think adding trips later on could be helpful for adding previous journeys or if your phone's battery died during the trip.

**Comment by derf** [comment]
Makes sense. I'll add manual trip entry and a trip edit function when I get around to it.
