### ISSUE TITLE
Include recent departures in frequent connections

### ISSUE THREAD

**Issue by Mq89** [derf/travelynx#33]
I think it would be convenient to include recent departures in the proposed frequent connections ("Häufig genutzte Verbindungen"). Say, the trains that departed 5 to 10 minutes to go.

I often check in a train once I have found a seat, i.e. after it departed. But at this point, my train does not appear on the proposed list anymore. The list however already shows the next train and I need to scroll down in the list of trains until I find `— Anfragezeitpunkt —` because my train is just below it.

**Comment by derf** [comment]
Indeed. I'll change the list to include recently departed trains in the station view and to show departures after arrival (as opposed to departures after now) in the "you're still checked in, do you want to change to another train?" panel

**Comment by Mq89** [comment]
cool. Thank you.
