### ISSUE TITLE
Distance on month/year summary doesn't equal the sum of the journey distances

### ISSUE THREAD

**Issue by lhaus** [derf/travelynx#40]
For some reason there is a rather large mismatch between single-journey distances added together and the displayed total distance of a month/year.  For example, in the month 03/2020 it displays 598km, and adding the displayed distances together results in 675 km. That's a pretty large mismatch, and I think that's unintended behavior.

**Comment by derf** [comment]
Journey details calculate distance based on the route reported by HAFAS (i.e., more or less the actual route taken). Stats are currently limited to beeline between intermediate stops and therefore under-estimate. I've been meaning to fix this, but didn't get around to it yet.

So: Known bug, thanks for the reminder :) should be fixed sometime over the next months
