### ISSUE TITLE
Traewelling-Verknüpfung: Error 500

### ISSUE THREAD

**Issue by JeDi-TS** [derf/travelynx#47]
Traewelling ist mit einem Error 500 nicht erreichbar. Beim Versuch, das Problem durch Abmelden und wieder Anmelden zu beheben, scheitert auch die Anmeldung bei Traewelling über die Schnittstelle ;-)

**Comment by MrKrisKrisu** [comment]
Das könnte an uns gelegen haben. Kannst du es noch einmal probieren, ob es jetzt klappt?
Wir hatten einen Krypto-Key beim Serverumzug vor zwei Tagen vergessen.

**Comment by JeDi-TS** [comment]
Jetzt hat sich das Fehlerbild verändert: Jetzt kommt ein HTTP 401 Unauthorized bei Abfrage der Nutzerdaten. Allerdings sehe ich bei Traewelling einen neu generierten API-Token...

It's not the error 500 anymore, but an error 401 (unauthorized) - nevertheless, travelling generated a new API-token...

**Comment by MrKrisKrisu** [comment]
@derf Can you tell me which Endpoint is failing now? I dont see any error on our side now.

**Comment by derf** [comment]
@MrKrisKrisu There appears to be an issue with Traewelling's Bearer Tokens. Previous tokens have been invalidated; tokens received after a fresh login do not work, even when doing so manually with `curl ... https://traewelling.de/api/v0/auth/login` and then `curl ... -H "Authorization: Bearer ...". Login works and returns a fresh token, however, using this token always results in 401 Unauthorized for me.

**Comment by JeDi-TS** [comment]
Solved
