### ISSUE TITLE
Line is missing stops

### ISSUE THREAD

**Issue by DerChaot** [derf/travelynx#48]
This issue is regarding the S3 from the HVV, but might be a problem for other lines too.

When I select a starting point from Buxtehude and I want to use the S3 to Pinneberg, I only get the first 3 stops to Hamburg-Neugraben. This issue is happening from every starting point from Stade to Neugraben. This might be because at Neugraben another train is coupled with the exist one to increase the size. Träwelling does not have this issue, so maybe you could check their Github.

https://www.nimmbus.de/fahrplanbuch/plaene/S3H-1.htm

**Comment by derf** [comment]
Fixed by the HAFAS introduction in 2023; I just forgot to update the issue.
