### ISSUE TITLE
Incorrect link to marudor from "Zuglauf"

### ISSUE THREAD

**Issue by GABRIELFILMSTUDIOS** [derf/travelynx#56]
The button "Zuglauf" sometimes links to the incorrect train on marudor.de.
When I was travelling on the IC 2310 to Westerland (Sylt) today, the button linked to the IC 2310 to Brussels Airport - Zaventem (https://marudor.de/details/IC%202310/1646039929000) instead.

**Comment by deingithub** [comment]
From what i've seen, trains with the same type and number could be disambiguated for bahn.expert by adding either `?station=[eva number along route]` or `?jid=[hafas journey id]` to the end of the details link. I can't find an example where it chooses the "wrong" train to demonstrate right now though.
