### ISSUE TITLE
Falsche HIM Meldung angezeigt

### ISSUE THREAD

**Issue by marudor** [derf/travelynx#59]
![image](https://user-images.githubusercontent.com/1881725/167025187-d9905b04-7fa6-470c-b919-43fa500119cd.jpeg)
Der Fernverkehr sollte wohl keine HIM Meldung aus NRW haben. 
Ich hab bei mir gegen gechecked ich zeig das nicht an, scheint also kein Fehler in den Quellen zu sein.

dbf zeigt die HIM Meldung auch nicht an. 
![image](https://user-images.githubusercontent.com/1881725/167025588-59e7a398-fbf9-4e8f-b4ed-488d0f8d9ebb.jpeg)

**Comment by marudor** [comment]
Das Problem hat sich übrigens über Zeit selbst gelöst. Inzwischen stehts nicht mehr dran am Zug.

**Comment by derf** [comment]
Nicht (mehr) reproduzierbar, sollte sich erledigt haben.
