### ISSUE TITLE
Träwelling Feature Login scheitert mit error 404

### ISSUE THREAD

**Issue by WilliamReed2004** [derf/travelynx#62]
![grafik](https://user-images.githubusercontent.com/29880819/201082503-d7ea0c9b-3d14-4511-b5bf-40c2f73d9bdd.png)
Beim Versuch meinen Träwelling Account to verknüpfen erscheint dieser Fehler

**Comment by MrKrisKrisu** [comment]
Siehe https://twitter.com/Traewelling/status/1585982577311113217

**Comment by derf** [comment]
Sollte ab v1.25.0 (soeben live auf travelynx.de) wieder tun
