### ISSUE TITLE
Fernverkehrslinien mit aufzeichnen 

### ISSUE THREAD

**Issue by jonaes** [derf/travelynx#63]
Es wäre schön, wenn auch zu Fernverkehrszügen die Liniennummer gespeichert werden würde, da dies aus meiner Sicht die Auswertungen sinnvoller machen würde.

Mindestens bei Marudor sollte diese auch verfügbar sein.

**Comment by derf** [comment]
Statische Daten habe ich auch (sind unter https://lib.finalrewind.org/dbdb/db_zugbildung_v1.json, das lässt sich also bereits von Hand zurechtbasteln). Aus den von mir verwendeten APIs scheint diese Information nicht zu fallen. Mal schauen.

**Comment by derf** [comment]
Ganz vergessen: Bei Checkins via "DB (HAFAS)" werden Fernverkehrslinien mit aufgezeichnet.
