### ISSUE TITLE
Journey nicht richtig abgeschlossen/auf den nächsten Tag verteilt

### ISSUE THREAD

**Issue by marudor** [derf/travelynx#67]
Wir haben fast zeitgleich in den Zug eingecheckt und sind ans gleiche Ziel gefahren.
Am nächsten Tag hab ich dann beim check in in einen anderen Zug die "Inkonsistente Reisedaten" Meldung bekommen. Dabei ist aufgefallen das meine Reise irgendwie auf den nächsten Tag gerutscht ist, aber check in war korrekt am Tag vorher.
Konkret war die Startzeit/Checkin korrekt am 29. (Abfahrt in Düsseldorf)
Die Ankunft war dann am 30. (Ankunft in EDO/Dortmund)

Ich hab inzwischen die Daten manuell korrigiert, aber die HIM Meldung ist noch vom Tag drauf. Hoffe du kannst da noch was nachvollziehen.
Meine Reise: https://travelynx.de/p/marudor/j/324302
Refrenz: https://travelynx.de/p/Tonda/j/323723

**Comment by derf** [comment]
Im Log finde ich nichts auffälliges. Hast du eventuell erst am 30. das Ziel ausgewählt, so dass ein Checkout überhaupt möglich war? In dem Fall kommen aus Edge Case-Gründen auch die Echtzeitdaten vom 30.

**Comment by marudor** [comment]
Hmm. Eigentlich meine ich das Ziel direkt ausgewählt zu haben.

Wenn ich kein Ziel ausgewählt habe aber am 30. in einen neuen Zug einchecke, werde ich dann in Dortmund ausgechecked? (Weil ich in Dortmund wieder eingechecked bin)
Falls ja kann theoretisch sein das ich noch eingechecked war.

In dem Fall wäre vmtl eine Lösung das ich automatisch ausgechecked werde nach X Stunden? (15 oder so)
Also bevor der Zugumlauf des nächsten Tages anfängt.

**Comment by derf** [comment]
> Wenn ich kein Ziel ausgewählt habe aber am 30. in einen neuen Zug einchecke, werde ich dann in Dortmund ausgechecked? (Weil ich in Dortmund wieder eingechecked bin)

Ja, genau das. Hab's gerade mal auf dev nachgestellt und gehe davon aus, dass bei dir genau das passiert ist.

Checkins mit vergessener Zielstation werden aktuell erst nach 48h automatisch gelöscht; mal gucken ob ich das ändere. Für den Moment denke ich, dass die aktuelle Lösung eine niedrigere Wahrscheinlichkeit für genau solche Bugs hat als eine alternative Lösung, die aggressiver vorgeht und früher Checkouts löscht.
