### ISSUE TITLE
Verbesserung für FGR-Formular 

### ISSUE THREAD

**Issue by TheWinHelper** [derf/travelynx#71]
Also am Sich muss ich das Projekt echt loben, hätte früher nie gedacht das ich es jemals brauchen würde aber Ich will das Tool inzwischen echt nicht mehr missen. Zwei Verbesserungsvorschläge hätte Ich aber noch für die automatische Erzeugung der FGR Formulare.

1. Eine Möglichkeit die eigenen Angaben (z.b. Anschrift etc) in Travelynx zu hinterlegen (natürlich freiwillig) sodass diese automatisch mit auf dem Fahrgastrechte Formular erscheinen. 

2. Praktisch wäre meiner Meinung nach eine Funktion, eine Fahrt in Travelynx als Ersatzfahrt zu markieren, z.b. Zug 1 fällt aus, daher Ankunft mit Zug 2 (also wie auf den FGR Formularen). 

Würde für mich das ganze noch praktischer machen, da es echt mühselig ist die Formulare immer von Hand auszufüllen. Aber gerade 2 wird vermutlich nicht ohne weiteres umsetzbar sein. Wenn's nicht umsetzbar ist wird der Dienst aber auch nicht schlechter dadurch.

**Comment by derf** [comment]
Moin!

> Eine Möglichkeit die eigenen Angaben (z.b. Anschrift etc) in Travelynx zu hinterlegen (natürlich freiwillig) sodass diese automatisch mit auf dem Fahrgastrechte Formular erscheinen.

Das gibt es bewusst nicht, um die in travelynx vorgehaltenen personenbezogenen Daten gering zu halten. Das FGR-Formular hat die meisten persönliche Angaben auf der ersten Seite und die Angaben zur Fahrt auf der zweiten, so dass man ganz gut bei jedem FGR-Fall die immer gleiche erste Seite selbst dazulegen kann.

> Praktisch wäre meiner Meinung nach eine Funktion, eine Fahrt in Travelynx als Ersatzfahrt zu markieren, z.b. Zug 1 fällt aus, daher Ankunft mit Zug 2 (also wie auf den FGR Formularen).

Langfristig habe ich die Idee, anstatt einzelner Zugfahrten ganze Reiseketten (also Verbindungen mit Umstiegen) in travelynx abzubilden. Dann lassen sich auch Ersatzfahrten unterbringen. Ob und wann das passieren wird, steht aber in den Sternen ;)

Ich mach das Issue mal zu da hier akut nichts zu tun ist; öffne es gerne wieder falls es noch weitere Punkte gibt oder ich etwas vergessen habe.
