### ISSUE TITLE
Should not be possible to check out of train at stop before checkin stop

### ISSUE THREAD

**Issue by mettaphysicist** [derf/travelynx#72]
Through some accidental taps as a newbie, I managed to check into a train at one stop, and then to check out at the stop just before. travelynx currently accepts this and then only complains when trying to compute total travel distance. 

I did this by checking into a train in advance at a stop that I had not yet reached, then checking out at the stop before that, where I happened to be. (I decided to change trains at the earlier of two stops where both trains stopped, instead of at the later one as originally planned.) I should have undone the checkin, rather than checking out again. 

As far as I can tell, travelynx shouldn't accept input that is logically impossible. I. e. it should refuse the checkout at a stop that lies before the checkin stop, and suggest "undo checkin". 

If someone tells me where to look, I might even take a stab at this myself.

**Comment by derf** [comment]
The original idea behind this behaviour was that when in doubt the user knows best, so they should be able to check out at a station even if it is not part of the route provided by the backend. This happens in rare occasions, typically when a train is diverted during large-scale disturbances.

However, you're absolutely right that this is confusing for new users.  I'll have travelynx issue a warning and offer to undo the checkin instead in these cases.
