### ISSUE TITLE
Bug(?): Usernames are case-sensitive

### ISSUE THREAD

**Issue by CherryKitten** [derf/travelynx#78]
When creating my account, I used "Cherrykitten" as my username. When trying to login, I tried with "cherrykitten" and got a login-error. Changing the name to start with Uppercase for the login worked.

Usernames are usually case-insensitive for login-purposes, so I'm assuming that this is unintended behaviour.

**Comment by derf** [comment]
That's by design and can't be changed now that there are travelynx instances out in the wild.

In hindsight, some sort of username normalization during registration and login may have been helpful.
