### ISSUE TITLE
Zugfahrt die außerplanmäßig früher endet wird auf der Karte nicht dargestellt

### ISSUE THREAD

**Issue by devNan0** [derf/travelynx#80]
Hey,

ich hatte eine Zugfahrt von Wien nach München Hbf die außerplanmäßig einen Halt in München Ost hatte und dort auch beendet wurde.
Diese wird jedoch nicht auf den Fahrkarten eingezeichnet.

Siehe: https://travelynx.de/journey/344259
Exakte Strecke: https://bahn.expert/details/RJX262/2023-05-25T06:28:00.000Z?administration=81

![image](https://github.com/derf/travelynx/assets/49376203/e4689ae2-aba0-4b7d-a645-851736922f64)

**Comment by derf** [comment]
Fixed in 772b4e3b23b10d3d628c29fac7a4eab6d05d686a
