### ISSUE TITLE
Timezone handling

### ISSUE THREAD

**Issue by gatecat** [derf/travelynx#91]
This is just a minor issue, but I noticed that when checked into a Eurostar service it doesn't take into account the timezone difference in the UK, so "Ankunft in 21 Minuten" should be actually 1h21.
![Screenshot_20231017-130903](https://github.com/derf/travelynx/assets/78621419/e7e627fc-ec0c-4b05-a7fb-6daebbf4e4d7)

**Comment by f2k1de** [comment]
Ähnliches Problem wenn der Browser eine andere Zeitzone als Travelynx hat. Dann springt beim neu Laden sogar die Uhrzeit vom Zwischenstopp eine Stunde. 

https://github.com/derf/travelynx/assets/11199213/61f56e1b-ffb2-4998-becf-9dd83407e0f5

Ganz davon abgesehen, dass durch den Zeitraum < 1h fürs Einchecken über die Stationssuche es nicht möglich ist, zur Abfahrtszeit in den Zug einzuchecken sondern man das immer $Zeitzonendifferenz Stunden vorher (oder später) machen muss.

**Comment by gatecat** [comment]
Seems like this should be fixed now
