### ISSUE TITLE
Fahrten des Schienenverkehrs werden falsch gespeichert wenn sie als Vorschläge aus dem Nahverkehr eingecheckt werden.

### ISSUE THREAD

**Issue by lollar1337** [derf/travelynx#99]
Wenn man mit der Strassenbahn einen Hbf ansteuert und dann auf den Vorschlägen einen Zug zb. IC/ICE auswählt wird dieser Zug anders gebucht. Es fehlt die Polyline auf der Karte und es wird auf die Linie gebucht. Siehe Screenshot als Beispiel.![image](https://github.com/derf/travelynx/assets/77240684/c9285122-243b-4971-a287-fbb5d8dbb3a4)![image](https://github.com/derf/travelynx/assets/77240684/3b084c32-f4d3-41f2-bb3c-b72dba91fb83)

**Comment by f2k1de** [comment]
Sicher, dass es sich dann um eine Fahrt aus der Datenquelle für Schienenverkehr handelt und nicht einfach genau so gehandhabt wird, wie wenn man jetzt auf der Abfahrtstafel für Dresden Hbf auf "zum Nahverkehr" auswählt und dort den IC auswählt? 

Dennoch sollten die halt dann verbunden sein.

**Comment by lollar1337** [comment]
Ich versuchs nochmal anders zu erklären. Wenn ich mit der Tram zum Hbf fahre schlägt er mir ja die "meist genutzten Züge" vor. Wenn ich diesen "Vorschlag" annehme dann wird es als Nahverkehrsfahrt gebucht mit den nahverkehrs Daten. Ist halt doof wenn man das nicht vorher weiss. Habe jetzt ein paar Linien durch ganz Deutschland weil ich von der 7 in einen ICE gestiegen bin.

**Comment by derf** [comment]
Ist ein bekanntes Problem und ich weiß genau woran es liegt, habe nur bisher keine Zeit mich drum zu kümmern.

**Comment by lollar1337** [comment]
Alles gut ich wollte es nur gemeldet haben
